server:
  port: 1401
  servlet:
    context-path: /api
spring:
  application:
    name: "suris-auth-service"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: auth
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: auth

jwt:
  secret: ${JWT_SECRET}
  expiration: 360000